-- Generated using RoadToGlory's Converter v1.1 (RoadToGlory#9879)

-- Instances:

local Converted = {
	["_Flow"] = Instance.new("ScreenGui");
	["_Container"] = Instance.new("Frame");
	["_Frame"] = Instance.new("Frame");
	["_UICorner"] = Instance.new("UICorner");
	["_Header"] = Instance.new("Frame");
	["_UICorner1"] = Instance.new("UICorner");
	["_Client"] = Instance.new("TextLabel");
	["_UITextSizeConstraint"] = Instance.new("UITextSizeConstraint");
	["_SearchBar"] = Instance.new("Frame");
	["_UICorner2"] = Instance.new("UICorner");
	["_Input"] = Instance.new("TextBox");
	["_UITextSizeConstraint1"] = Instance.new("UITextSizeConstraint");
	["_UIPadding"] = Instance.new("UIPadding");
	["_IconBG"] = Instance.new("ImageLabel");
	["_Icon"] = Instance.new("ImageLabel");
	["_Tabs"] = Instance.new("ScrollingFrame");
	["_UIListLayout"] = Instance.new("UIListLayout");
	["_Tab"] = Instance.new("TextButton");
	["_UICorner3"] = Instance.new("UICorner");
	["_Icon1"] = Instance.new("ImageLabel");
	["_Title"] = Instance.new("TextLabel");
	["_UITextSizeConstraint2"] = Instance.new("UITextSizeConstraint");
	["_Sections"] = Instance.new("Folder");
	["_LeftSection"] = Instance.new("ScrollingFrame");
	["_UIListLayout1"] = Instance.new("UIListLayout");
	["_Module"] = Instance.new("Frame");
	["_UICorner4"] = Instance.new("UICorner");
	["_Settings"] = Instance.new("Frame");
	["_UIListLayout2"] = Instance.new("UIListLayout");
	["_Dropdown"] = Instance.new("TextButton");
	["_UIPadding1"] = Instance.new("UIPadding");
	["_Title1"] = Instance.new("TextLabel");
	["_UITextSizeConstraint3"] = Instance.new("UITextSizeConstraint");
	["_Box"] = Instance.new("Frame");
	["_UICorner5"] = Instance.new("UICorner");
	["_Options"] = Instance.new("Frame");
	["_List"] = Instance.new("ScrollingFrame");
	["_UIListLayout3"] = Instance.new("UIListLayout");
	["_Option"] = Instance.new("TextButton");
	["_UITextSizeConstraint4"] = Instance.new("UITextSizeConstraint");
	["_UIGradient"] = Instance.new("UIGradient");
	["_Option1"] = Instance.new("TextButton");
	["_UITextSizeConstraint5"] = Instance.new("UITextSizeConstraint");
	["_UIGradient1"] = Instance.new("UIGradient");
	["_Option2"] = Instance.new("TextButton");
	["_UITextSizeConstraint6"] = Instance.new("UITextSizeConstraint");
	["_UIGradient2"] = Instance.new("UIGradient");
	["_Option3"] = Instance.new("TextButton");
	["_UITextSizeConstraint7"] = Instance.new("UITextSizeConstraint");
	["_UIGradient3"] = Instance.new("UIGradient");
	["_Option4"] = Instance.new("TextButton");
	["_UITextSizeConstraint8"] = Instance.new("UITextSizeConstraint");
	["_UIGradient4"] = Instance.new("UIGradient");
	["_Fill"] = Instance.new("Frame");
	["_Corner"] = Instance.new("ImageLabel");
	["_Header1"] = Instance.new("ImageLabel");
	["_Arrow"] = Instance.new("ImageLabel");
	["_Option5"] = Instance.new("TextLabel");
	["_UITextSizeConstraint9"] = Instance.new("UITextSizeConstraint");
	["_UIGradient5"] = Instance.new("UIGradient");
	["_Slider"] = Instance.new("TextButton");
	["_Drag"] = Instance.new("Frame");
	["_UICorner6"] = Instance.new("UICorner");
	["_Fill1"] = Instance.new("Frame");
	["_UICorner7"] = Instance.new("UICorner");
	["_Circle"] = Instance.new("Frame");
	["_UICorner8"] = Instance.new("UICorner");
	["_Title2"] = Instance.new("TextLabel");
	["_UITextSizeConstraint10"] = Instance.new("UITextSizeConstraint");
	["_Value"] = Instance.new("TextLabel");
	["_UITextSizeConstraint11"] = Instance.new("UITextSizeConstraint");
	["_Header2"] = Instance.new("ImageButton");
	["_Arrow1"] = Instance.new("ImageLabel");
	["_Keybind"] = Instance.new("TextButton");
	["_Background"] = Instance.new("Frame");
	["_UICorner9"] = Instance.new("UICorner");
	["_String"] = Instance.new("TextLabel");
	["_UITextSizeConstraint12"] = Instance.new("UITextSizeConstraint");
	["_Delete"] = Instance.new("ImageLabel");
	["_Edit"] = Instance.new("ImageLabel");
	["_Title3"] = Instance.new("TextLabel");
	["_UITextSizeConstraint13"] = Instance.new("UITextSizeConstraint");
	["_RightSection"] = Instance.new("ScrollingFrame");
	["_UIListLayout4"] = Instance.new("UIListLayout");
	["_UIScale"] = Instance.new("UIScale");
	["_UIAspectRatioConstraint"] = Instance.new("UIAspectRatioConstraint");
	["_Mobile"] = Instance.new("TextButton");
	["_UICorner10"] = Instance.new("UICorner");
	["_Icon2"] = Instance.new("ImageLabel");
	["_UIAspectRatioConstraint1"] = Instance.new("UIAspectRatioConstraint");
}

-- Properties:

Converted["_Flow"].ZIndexBehavior = Enum.ZIndexBehavior.Sibling
Converted["_Flow"].Name = "Flow"
Converted["_Flow"].Parent = game:GetService("CoreGui")

Converted["_Container"].Active = true
Converted["_Container"].AnchorPoint = Vector2.new(0.5, 0.5)
Converted["_Container"].BackgroundColor3 = Color3.fromRGB(13.000000175088644, 13.000000175088644, 13.000000175088644)
Converted["_Container"].BackgroundTransparency = 0.10000000149011612
Converted["_Container"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Container"].BorderSizePixel = 0
Converted["_Container"].Position = UDim2.new(0.5, 0, 0.493500471, 0)
Converted["_Container"].Size = UDim2.new(0, 640, 0, 355)
Converted["_Container"].Name = "Container"
Converted["_Container"].Parent = Converted["_Flow"]

Converted["_Frame"].AnchorPoint = Vector2.new(0.5, 0.5)
Converted["_Frame"].BackgroundTransparency = 1
Converted["_Frame"].Position = UDim2.new(0.5, 0, 0.5, 0)
Converted["_Frame"].Size = UDim2.new(0.949999988, 0, 0.949999988, 0)
Converted["_Frame"].Parent = Converted["_Container"]

Converted["_UICorner"].CornerRadius = UDim.new(0, 10)
Converted["_UICorner"].Parent = Converted["_Container"]

Converted["_Header"].BackgroundColor3 = Color3.fromRGB(27.000000290572643, 27.000000290572643, 27.000000290572643)
Converted["_Header"].BackgroundTransparency = 0.5
Converted["_Header"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Header"].BorderSizePixel = 0
Converted["_Header"].Position = UDim2.new(0.0125000002, 0, 0.0225352105, 0)
Converted["_Header"].Size = UDim2.new(0, 624, 0, 24)
Converted["_Header"].Name = "Header"
Converted["_Header"].Parent = Converted["_Container"]

Converted["_UICorner1"].CornerRadius = UDim.new(0, 5)
Converted["_UICorner1"].Parent = Converted["_Header"]

Converted["_Client"].Font = Enum.Font.Unknown
Converted["_Client"].Text = "Flow"
Converted["_Client"].TextColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Client"].TextScaled = true
Converted["_Client"].TextSize = 14
Converted["_Client"].TextWrapped = true
Converted["_Client"].TextXAlignment = Enum.TextXAlignment.Left
Converted["_Client"].AnchorPoint = Vector2.new(0, 0.5)
Converted["_Client"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Client"].BackgroundTransparency = 1
Converted["_Client"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Client"].BorderSizePixel = 0
Converted["_Client"].Position = UDim2.new(0.0439999998, 0, 0.5, 0)
Converted["_Client"].Size = UDim2.new(0, 78, 0, 12)
Converted["_Client"].Name = "Client"
Converted["_Client"].Parent = Converted["_Header"]

Converted["_UITextSizeConstraint"].MaxTextSize = 12
Converted["_UITextSizeConstraint"].MinTextSize = 12
Converted["_UITextSizeConstraint"].Parent = Converted["_Client"]

Converted["_SearchBar"].AnchorPoint = Vector2.new(1, 0.5)
Converted["_SearchBar"].BackgroundColor3 = Color3.fromRGB(33.00000183284283, 33.00000183284283, 33.00000183284283)
Converted["_SearchBar"].BackgroundTransparency = 0.5
Converted["_SearchBar"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_SearchBar"].BorderSizePixel = 0
Converted["_SearchBar"].Position = UDim2.new(0.995000005, 0, 0.5, 0)
Converted["_SearchBar"].Size = UDim2.new(0, 64, 0, 17)
Converted["_SearchBar"].Name = "SearchBar"
Converted["_SearchBar"].Parent = Converted["_Header"]

Converted["_UICorner2"].CornerRadius = UDim.new(0, 4)
Converted["_UICorner2"].Parent = Converted["_SearchBar"]

Converted["_Input"].ClearTextOnFocus = false
Converted["_Input"].Font = Enum.Font.Unknown
Converted["_Input"].PlaceholderColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Input"].PlaceholderText = "Search"
Converted["_Input"].Text = ""
Converted["_Input"].TextColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Input"].TextSize = 10
Converted["_Input"].TextTransparency = 0.5
Converted["_Input"].TextWrapped = true
Converted["_Input"].TextXAlignment = Enum.TextXAlignment.Left
Converted["_Input"].AnchorPoint = Vector2.new(0, 0.5)
Converted["_Input"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Input"].BackgroundTransparency = 1
Converted["_Input"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Input"].BorderSizePixel = 0
Converted["_Input"].Position = UDim2.new(0, 0, 0.5, 0)
Converted["_Input"].Size = UDim2.new(0, 39, 0, 14)
Converted["_Input"].Name = "Input"
Converted["_Input"].Parent = Converted["_SearchBar"]

Converted["_UITextSizeConstraint1"].MaxTextSize = 10
Converted["_UITextSizeConstraint1"].MinTextSize = 10
Converted["_UITextSizeConstraint1"].Parent = Converted["_Input"]

Converted["_UIPadding"].PaddingLeft = UDim.new(0, 9)
Converted["_UIPadding"].Parent = Converted["_SearchBar"]

Converted["_IconBG"].Image = "rbxassetid://137743164814611"
Converted["_IconBG"].AnchorPoint = Vector2.new(1, 0.5)
Converted["_IconBG"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_IconBG"].BackgroundTransparency = 1
Converted["_IconBG"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_IconBG"].BorderSizePixel = 0
Converted["_IconBG"].Position = UDim2.new(1, 0, 0.5, 0)
Converted["_IconBG"].Size = UDim2.new(0, 17, 0, 17)
Converted["_IconBG"].Name = "IconBG"
Converted["_IconBG"].Parent = Converted["_SearchBar"]

Converted["_Icon"].Image = "rbxassetid://86686259429503"
Converted["_Icon"].AnchorPoint = Vector2.new(0.5, 0.5)
Converted["_Icon"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Icon"].BackgroundTransparency = 1
Converted["_Icon"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Icon"].BorderSizePixel = 0
Converted["_Icon"].Position = UDim2.new(0.5, 0, 0.5, 0)
Converted["_Icon"].Size = UDim2.new(0, 9, 0, 9)
Converted["_Icon"].Name = "Icon"
Converted["_Icon"].Parent = Converted["_IconBG"]

Converted["_Tabs"].AutomaticCanvasSize = Enum.AutomaticSize.X
Converted["_Tabs"].CanvasSize = UDim2.new(0, 0, 0.5, 0)
Converted["_Tabs"].ScrollBarImageColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Tabs"].ScrollBarImageTransparency = 1
Converted["_Tabs"].ScrollBarThickness = 0
Converted["_Tabs"].Active = true
Converted["_Tabs"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Tabs"].BackgroundTransparency = 1
Converted["_Tabs"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Tabs"].BorderSizePixel = 0
Converted["_Tabs"].Position = UDim2.new(0.0125000002, 0, 0.109859154, 0)
Converted["_Tabs"].Size = UDim2.new(0, 138, 0, 308)
Converted["_Tabs"].Name = "Tabs"
Converted["_Tabs"].Parent = Converted["_Container"]

Converted["_UIListLayout"].Padding = UDim.new(0, 6)
Converted["_UIListLayout"].SortOrder = Enum.SortOrder.LayoutOrder
Converted["_UIListLayout"].Parent = Converted["_Tabs"]

Converted["_Tab"].Font = Enum.Font.SourceSans
Converted["_Tab"].Text = ""
Converted["_Tab"].TextColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Tab"].TextSize = 14
Converted["_Tab"].AutoButtonColor = false
Converted["_Tab"].BackgroundColor3 = Color3.fromRGB(27.000000290572643, 27.000000290572643, 27.000000290572643)
Converted["_Tab"].BackgroundTransparency = 0.5
Converted["_Tab"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Tab"].BorderSizePixel = 0
Converted["_Tab"].Size = UDim2.new(0, 138, 0, 27)
Converted["_Tab"].Name = "Tab"
Converted["_Tab"].Parent = Converted["_Tabs"]

Converted["_UICorner3"].CornerRadius = UDim.new(0, 5)
Converted["_UICorner3"].Parent = Converted["_Tab"]

Converted["_Icon1"].Image = "rbxassetid://10709810463"
Converted["_Icon1"].AnchorPoint = Vector2.new(0, 0.5)
Converted["_Icon1"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Icon1"].BackgroundTransparency = 1
Converted["_Icon1"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Icon1"].BorderSizePixel = 0
Converted["_Icon1"].Position = UDim2.new(0.100000001, 0, 0.5, 0)
Converted["_Icon1"].Size = UDim2.new(0, 12, 0, 12)
Converted["_Icon1"].Name = "Icon"
Converted["_Icon1"].Parent = Converted["_Tab"]

Converted["_Title"].Font = Enum.Font.Unknown
Converted["_Title"].Text = "Blatant"
Converted["_Title"].TextColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Title"].TextScaled = true
Converted["_Title"].TextSize = 14
Converted["_Title"].TextWrapped = true
Converted["_Title"].TextXAlignment = Enum.TextXAlignment.Left
Converted["_Title"].AnchorPoint = Vector2.new(0, 0.5)
Converted["_Title"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Title"].BackgroundTransparency = 1
Converted["_Title"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Title"].BorderSizePixel = 0
Converted["_Title"].Position = UDim2.new(0.224999905, 0, 0.5, 0)
Converted["_Title"].Size = UDim2.new(0, 75, 0, 12)
Converted["_Title"].Name = "Title"
Converted["_Title"].Parent = Converted["_Tab"]

Converted["_UITextSizeConstraint2"].MaxTextSize = 12
Converted["_UITextSizeConstraint2"].MinTextSize = 12
Converted["_UITextSizeConstraint2"].Parent = Converted["_Title"]

Converted["_Sections"].Name = "Sections"
Converted["_Sections"].Parent = Converted["_Container"]

Converted["_LeftSection"].AutomaticCanvasSize = Enum.AutomaticSize.XY
Converted["_LeftSection"].CanvasSize = UDim2.new(0, 0, 0.5, 0)
Converted["_LeftSection"].ScrollBarImageColor3 = Color3.fromRGB(0, 0, 0)
Converted["_LeftSection"].ScrollBarImageTransparency = 1
Converted["_LeftSection"].ScrollBarThickness = 0
Converted["_LeftSection"].Active = true
Converted["_LeftSection"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_LeftSection"].BackgroundTransparency = 1
Converted["_LeftSection"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_LeftSection"].BorderSizePixel = 0
Converted["_LeftSection"].Position = UDim2.new(0.239999995, 0, 0.109999999, 0)
Converted["_LeftSection"].Size = UDim2.new(0, 237, 0, 306)
Converted["_LeftSection"].Name = "LeftSection"
Converted["_LeftSection"].Parent = Converted["_Sections"]

Converted["_UIListLayout1"].Padding = UDim.new(0, 6)
Converted["_UIListLayout1"].Parent = Converted["_LeftSection"]

Converted["_Module"].BackgroundColor3 = Color3.fromRGB(27.000000290572643, 27.000000290572643, 27.000000290572643)
Converted["_Module"].BackgroundTransparency = 0.5
Converted["_Module"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Module"].BorderSizePixel = 0
Converted["_Module"].ClipsDescendants = true
Converted["_Module"].Size = UDim2.new(0, 237, 0, 189)
Converted["_Module"].Name = "Module"
Converted["_Module"].Parent = Converted["_LeftSection"]

Converted["_UICorner4"].CornerRadius = UDim.new(0, 5)
Converted["_UICorner4"].Parent = Converted["_Module"]

Converted["_Settings"].AnchorPoint = Vector2.new(0, 1)
Converted["_Settings"].BackgroundColor3 = Color3.fromRGB(27.000000290572643, 27.000000290572643, 27.000000290572643)
Converted["_Settings"].BackgroundTransparency = 1
Converted["_Settings"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Settings"].BorderSizePixel = 0
Converted["_Settings"].ClipsDescendants = true
Converted["_Settings"].Position = UDim2.new(0, 0, 1, 0)
Converted["_Settings"].Size = UDim2.new(0, 237, 0, 161)
Converted["_Settings"].Name = "Settings"
Converted["_Settings"].Parent = Converted["_Module"]

Converted["_UIListLayout2"].HorizontalAlignment = Enum.HorizontalAlignment.Center
Converted["_UIListLayout2"].SortOrder = Enum.SortOrder.LayoutOrder
Converted["_UIListLayout2"].VerticalAlignment = Enum.VerticalAlignment.Center
Converted["_UIListLayout2"].Parent = Converted["_Settings"]

Converted["_Dropdown"].Font = Enum.Font.SourceSans
Converted["_Dropdown"].Text = ""
Converted["_Dropdown"].TextColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Dropdown"].TextSize = 14
Converted["_Dropdown"].AutoButtonColor = false
Converted["_Dropdown"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Dropdown"].BackgroundTransparency = 1
Converted["_Dropdown"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Dropdown"].BorderSizePixel = 0
Converted["_Dropdown"].Size = UDim2.new(0, 216, 0, 127)
Converted["_Dropdown"].Name = "Dropdown"
Converted["_Dropdown"].Parent = Converted["_Settings"]

Converted["_UIPadding1"].PaddingTop = UDim.new(0, 3)
Converted["_UIPadding1"].Parent = Converted["_Dropdown"]

Converted["_Title1"].Font = Enum.Font.GothamMedium
Converted["_Title1"].Text = ""
Converted["_Title1"].TextColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Title1"].TextScaled = true
Converted["_Title1"].TextSize = 14
Converted["_Title1"].TextTransparency = 0.5
Converted["_Title1"].TextWrapped = true
Converted["_Title1"].TextXAlignment = Enum.TextXAlignment.Left
Converted["_Title1"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Title1"].BackgroundTransparency = 1
Converted["_Title1"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Title1"].BorderSizePixel = 0
Converted["_Title1"].Size = UDim2.new(0, 215, 0, 12)
Converted["_Title1"].Name = "Title"
Converted["_Title1"].Parent = Converted["_Dropdown"]

Converted["_UITextSizeConstraint3"].MaxTextSize = 12
Converted["_UITextSizeConstraint3"].MinTextSize = 12
Converted["_UITextSizeConstraint3"].Parent = Converted["_Title1"]

Converted["_Box"].AnchorPoint = Vector2.new(0.5, 0)
Converted["_Box"].BackgroundColor3 = Color3.fromRGB(48.000000938773155, 48.000000938773155, 48.000000938773155)
Converted["_Box"].BackgroundTransparency = 1
Converted["_Box"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Box"].BorderSizePixel = 0
Converted["_Box"].Position = UDim2.new(0.5, 0, 1.29999995, 0)
Converted["_Box"].Size = UDim2.new(0, 218, 0, 18)
Converted["_Box"].Name = "Box"
Converted["_Box"].Parent = Converted["_Title1"]

Converted["_UICorner5"].CornerRadius = UDim.new(0, 5)
Converted["_UICorner5"].Parent = Converted["_Box"]

Converted["_Options"].AnchorPoint = Vector2.new(0.5, 0)
Converted["_Options"].BackgroundColor3 = Color3.fromRGB(35.00000171363354, 35.00000171363354, 35.00000171363354)
Converted["_Options"].BackgroundTransparency = 1
Converted["_Options"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Options"].BorderSizePixel = 0
Converted["_Options"].ClipsDescendants = true
Converted["_Options"].Position = UDim2.new(0.5, 0, 1.0999999, 0)
Converted["_Options"].Size = UDim2.new(0, 218, 0, 85)
Converted["_Options"].Name = "Options"
Converted["_Options"].Parent = Converted["_Box"]

Converted["_List"].AutomaticCanvasSize = Enum.AutomaticSize.XY
Converted["_List"].CanvasSize = UDim2.new(0, 0, 0.5, 0)
Converted["_List"].ScrollBarImageColor3 = Color3.fromRGB(0, 0, 0)
Converted["_List"].ScrollBarImageTransparency = 1
Converted["_List"].ScrollBarThickness = 0
Converted["_List"].Active = true
Converted["_List"].AnchorPoint = Vector2.new(0.5, 0)
Converted["_List"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_List"].BackgroundTransparency = 1
Converted["_List"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_List"].BorderSizePixel = 0
Converted["_List"].Position = UDim2.new(0.5, 0, 0, 0)
Converted["_List"].Size = UDim2.new(0, 218, 0, 85)
Converted["_List"].Name = "List"
Converted["_List"].Parent = Converted["_Options"]

Converted["_UIListLayout3"].HorizontalAlignment = Enum.HorizontalAlignment.Center
Converted["_UIListLayout3"].Parent = Converted["_List"]

Converted["_Option"].Font = Enum.Font.GothamMedium
Converted["_Option"].Text = "Camera"
Converted["_Option"].TextColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Option"].TextSize = 12
Converted["_Option"].TextTransparency = 0.5
Converted["_Option"].TextXAlignment = Enum.TextXAlignment.Left
Converted["_Option"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Option"].BackgroundTransparency = 1
Converted["_Option"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Option"].BorderSizePixel = 0
Converted["_Option"].Size = UDim2.new(0, 205, 0, 17)
Converted["_Option"].ZIndex = 2
Converted["_Option"].Name = "Option"
Converted["_Option"].Parent = Converted["_List"]

Converted["_UITextSizeConstraint4"].MaxTextSize = 12
Converted["_UITextSizeConstraint4"].MinTextSize = 12
Converted["_UITextSizeConstraint4"].Parent = Converted["_Option"]

Converted["_UIGradient"].Transparency = NumberSequence.new{
	NumberSequenceKeypoint.new(0, 0),
	NumberSequenceKeypoint.new(0.7581047415733337, 0),
	NumberSequenceKeypoint.new(0.9301745891571045, 0.26875001192092896),
	NumberSequenceKeypoint.new(1, 1)
}
Converted["_UIGradient"].Parent = Converted["_Option"]

Converted["_Option1"].Font = Enum.Font.GothamMedium
Converted["_Option1"].Text = "Backwards"
Converted["_Option1"].TextColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Option1"].TextSize = 12
Converted["_Option1"].TextTransparency = 0.800000011920929
Converted["_Option1"].TextXAlignment = Enum.TextXAlignment.Left
Converted["_Option1"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Option1"].BackgroundTransparency = 1
Converted["_Option1"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Option1"].BorderSizePixel = 0
Converted["_Option1"].Size = UDim2.new(0, 205, 0, 17)
Converted["_Option1"].ZIndex = 2
Converted["_Option1"].Name = "Option"
Converted["_Option1"].Parent = Converted["_List"]

Converted["_UITextSizeConstraint5"].MaxTextSize = 12
Converted["_UITextSizeConstraint5"].MinTextSize = 12
Converted["_UITextSizeConstraint5"].Parent = Converted["_Option1"]

Converted["_UIGradient1"].Transparency = NumberSequence.new{
	NumberSequenceKeypoint.new(0, 0),
	NumberSequenceKeypoint.new(0.7581047415733337, 0),
	NumberSequenceKeypoint.new(0.9301745891571045, 0.26875001192092896),
	NumberSequenceKeypoint.new(1, 1)
}
Converted["_UIGradient1"].Parent = Converted["_Option1"]

Converted["_Option2"].Font = Enum.Font.GothamMedium
Converted["_Option2"].Text = "Straight"
Converted["_Option2"].TextColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Option2"].TextSize = 12
Converted["_Option2"].TextTransparency = 0.800000011920929
Converted["_Option2"].TextXAlignment = Enum.TextXAlignment.Left
Converted["_Option2"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Option2"].BackgroundTransparency = 1
Converted["_Option2"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Option2"].BorderSizePixel = 0
Converted["_Option2"].Size = UDim2.new(0, 205, 0, 17)
Converted["_Option2"].ZIndex = 2
Converted["_Option2"].Name = "Option"
Converted["_Option2"].Parent = Converted["_List"]

Converted["_UITextSizeConstraint6"].MaxTextSize = 12
Converted["_UITextSizeConstraint6"].MinTextSize = 12
Converted["_UITextSizeConstraint6"].Parent = Converted["_Option2"]

Converted["_UIGradient2"].Transparency = NumberSequence.new{
	NumberSequenceKeypoint.new(0, 0),
	NumberSequenceKeypoint.new(0.7581047415733337, 0),
	NumberSequenceKeypoint.new(0.9301745891571045, 0.26875001192092896),
	NumberSequenceKeypoint.new(1, 1)
}
Converted["_UIGradient2"].Parent = Converted["_Option2"]

Converted["_Option3"].Font = Enum.Font.GothamMedium
Converted["_Option3"].Text = "High"
Converted["_Option3"].TextColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Option3"].TextSize = 12
Converted["_Option3"].TextTransparency = 0.800000011920929
Converted["_Option3"].TextXAlignment = Enum.TextXAlignment.Left
Converted["_Option3"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Option3"].BackgroundTransparency = 1
Converted["_Option3"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Option3"].BorderSizePixel = 0
Converted["_Option3"].Size = UDim2.new(0, 205, 0, 17)
Converted["_Option3"].ZIndex = 2
Converted["_Option3"].Name = "Option"
Converted["_Option3"].Parent = Converted["_List"]

Converted["_UITextSizeConstraint7"].MaxTextSize = 12
Converted["_UITextSizeConstraint7"].MinTextSize = 12
Converted["_UITextSizeConstraint7"].Parent = Converted["_Option3"]

Converted["_UIGradient3"].Transparency = NumberSequence.new{
	NumberSequenceKeypoint.new(0, 0),
	NumberSequenceKeypoint.new(0.7581047415733337, 0),
	NumberSequenceKeypoint.new(0.9301745891571045, 0.26875001192092896),
	NumberSequenceKeypoint.new(1, 1)
}
Converted["_UIGradient3"].Parent = Converted["_Option3"]

Converted["_Option4"].Font = Enum.Font.GothamMedium
Converted["_Option4"].Text = "Random"
Converted["_Option4"].TextColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Option4"].TextSize = 12
Converted["_Option4"].TextTransparency = 0.800000011920929
Converted["_Option4"].TextXAlignment = Enum.TextXAlignment.Left
Converted["_Option4"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Option4"].BackgroundTransparency = 1
Converted["_Option4"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Option4"].BorderSizePixel = 0
Converted["_Option4"].Size = UDim2.new(0, 205, 0, 17)
Converted["_Option4"].ZIndex = 2
Converted["_Option4"].Name = "Option"
Converted["_Option4"].Parent = Converted["_List"]

Converted["_UITextSizeConstraint8"].MaxTextSize = 12
Converted["_UITextSizeConstraint8"].MinTextSize = 12
Converted["_UITextSizeConstraint8"].Parent = Converted["_Option4"]

Converted["_UIGradient4"].Transparency = NumberSequence.new{
	NumberSequenceKeypoint.new(0, 0),
	NumberSequenceKeypoint.new(0.7581047415733337, 0),
	NumberSequenceKeypoint.new(0.9301745891571045, 0.26875001192092896),
	NumberSequenceKeypoint.new(1, 1)
}
Converted["_UIGradient4"].Parent = Converted["_Option4"]

Converted["_Fill"].BackgroundColor3 = Color3.fromRGB(35.00000171363354, 35.00000171363354, 35.00000171363354)
Converted["_Fill"].BackgroundTransparency = 0.5
Converted["_Fill"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Fill"].BorderSizePixel = 0
Converted["_Fill"].Position = UDim2.new(0, 0, -0.0500000007, 0)
Converted["_Fill"].Size = UDim2.new(0, 218, 0, 89)
Converted["_Fill"].Name = "Fill"
Converted["_Fill"].Parent = Converted["_Options"]

Converted["_Corner"].Image = "rbxassetid://130629302605775"
Converted["_Corner"].ImageTransparency = 0.5
Converted["_Corner"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Corner"].BackgroundTransparency = 1
Converted["_Corner"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Corner"].BorderSizePixel = 0
Converted["_Corner"].Position = UDim2.new(0, 0, 1, 0)
Converted["_Corner"].Size = UDim2.new(0, 218, 0, 10)
Converted["_Corner"].Name = "Corner"
Converted["_Corner"].Parent = Converted["_Fill"]

Converted["_Header1"].Image = "rbxassetid://70783523951929"
Converted["_Header1"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Header1"].BackgroundTransparency = 1
Converted["_Header1"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Header1"].BorderSizePixel = 0
Converted["_Header1"].Position = UDim2.new(0, 0, -0.5, 0)
Converted["_Header1"].Size = UDim2.new(0, 218, 0, 18)
Converted["_Header1"].Name = "Header"
Converted["_Header1"].Parent = Converted["_Box"]

Converted["_Arrow"].Image = "rbxassetid://136776761805636"
Converted["_Arrow"].ImageTransparency = 0.5
Converted["_Arrow"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Arrow"].BackgroundTransparency = 1
Converted["_Arrow"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Arrow"].BorderSizePixel = 0
Converted["_Arrow"].Position = UDim2.new(0.930000007, 0, 0.25, 0)
Converted["_Arrow"].Rotation = -90
Converted["_Arrow"].Size = UDim2.new(0, 10, 0, 10)
Converted["_Arrow"].Name = "Arrow"
Converted["_Arrow"].Parent = Converted["_Header1"]

Converted["_Option5"].Font = Enum.Font.GothamMedium
Converted["_Option5"].Text = "Camera"
Converted["_Option5"].TextColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Option5"].TextSize = 12
Converted["_Option5"].TextTransparency = 0.5
Converted["_Option5"].TextXAlignment = Enum.TextXAlignment.Left
Converted["_Option5"].AnchorPoint = Vector2.new(0.5, 0)
Converted["_Option5"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Option5"].BackgroundTransparency = 1
Converted["_Option5"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Option5"].BorderSizePixel = 0
Converted["_Option5"].Position = UDim2.new(0.5, 0, 0.0999999642, 0)
Converted["_Option5"].Size = UDim2.new(0, 194, 0, 12)
Converted["_Option5"].Name = "Option"
Converted["_Option5"].Parent = Converted["_Header1"]

Converted["_UITextSizeConstraint9"].MaxTextSize = 12
Converted["_UITextSizeConstraint9"].MinTextSize = 12
Converted["_UITextSizeConstraint9"].Parent = Converted["_Option5"]

Converted["_UIGradient5"].Transparency = NumberSequence.new{
	NumberSequenceKeypoint.new(0, 0),
	NumberSequenceKeypoint.new(0.7581047415733337, 0),
	NumberSequenceKeypoint.new(0.9301745891571045, 0.26875001192092896),
	NumberSequenceKeypoint.new(1, 1)
}
Converted["_UIGradient5"].Parent = Converted["_Option5"]

Converted["_Slider"].Font = Enum.Font.SourceSans
Converted["_Slider"].Text = ""
Converted["_Slider"].TextColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Slider"].TextSize = 14
Converted["_Slider"].AutoButtonColor = false
Converted["_Slider"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Slider"].BackgroundTransparency = 1
Converted["_Slider"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Slider"].BorderSizePixel = 0
Converted["_Slider"].Size = UDim2.new(0, 216, 0, 27)
Converted["_Slider"].Name = "Slider"
Converted["_Slider"].Parent = Converted["_Settings"]

Converted["_Drag"].AnchorPoint = Vector2.new(0.5, 1)
Converted["_Drag"].BackgroundColor3 = Color3.fromRGB(48.000000938773155, 48.000000938773155, 48.000000938773155)
Converted["_Drag"].BackgroundTransparency = 0.5
Converted["_Drag"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Drag"].BorderSizePixel = 0
Converted["_Drag"].Position = UDim2.new(0.5, 0, 0.800000012, 0)
Converted["_Drag"].Size = UDim2.new(0, 217, 0, 4)
Converted["_Drag"].Name = "Drag"
Converted["_Drag"].Parent = Converted["_Slider"]

Converted["_UICorner6"].Parent = Converted["_Drag"]

Converted["_Fill1"].AnchorPoint = Vector2.new(0, 0.5)
Converted["_Fill1"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Fill1"].BackgroundTransparency = 0.5
Converted["_Fill1"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Fill1"].BorderSizePixel = 0
Converted["_Fill1"].Position = UDim2.new(0, 0, 0.5, 0)
Converted["_Fill1"].Size = UDim2.new(0, 217, 0, 4)
Converted["_Fill1"].Name = "Fill"
Converted["_Fill1"].Parent = Converted["_Drag"]

Converted["_UICorner7"].Parent = Converted["_Fill1"]

Converted["_Circle"].AnchorPoint = Vector2.new(1, 0.5)
Converted["_Circle"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Circle"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Circle"].BorderSizePixel = 0
Converted["_Circle"].Position = UDim2.new(1, 0, 0.5, 0)
Converted["_Circle"].Size = UDim2.new(0, 6, 0, 6)
Converted["_Circle"].Name = "Circle"
Converted["_Circle"].Parent = Converted["_Fill1"]

Converted["_UICorner8"].CornerRadius = UDim.new(1, 0)
Converted["_UICorner8"].Parent = Converted["_Circle"]

Converted["_Title2"].Font = Enum.Font.GothamMedium
Converted["_Title2"].Text = "Accuracy"
Converted["_Title2"].TextColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Title2"].TextScaled = true
Converted["_Title2"].TextSize = 14
Converted["_Title2"].TextTransparency = 0.5
Converted["_Title2"].TextWrapped = true
Converted["_Title2"].TextXAlignment = Enum.TextXAlignment.Left
Converted["_Title2"].AnchorPoint = Vector2.new(0, 0.5)
Converted["_Title2"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Title2"].BackgroundTransparency = 1
Converted["_Title2"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Title2"].BorderSizePixel = 0
Converted["_Title2"].Position = UDim2.new(0, 0, 0.400000006, 0)
Converted["_Title2"].Size = UDim2.new(0, 172, 0, 12)
Converted["_Title2"].Name = "Title"
Converted["_Title2"].Parent = Converted["_Slider"]

Converted["_UITextSizeConstraint10"].MaxTextSize = 12
Converted["_UITextSizeConstraint10"].MinTextSize = 12
Converted["_UITextSizeConstraint10"].Parent = Converted["_Title2"]

Converted["_Value"].Font = Enum.Font.GothamMedium
Converted["_Value"].Text = "100"
Converted["_Value"].TextColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Value"].TextScaled = true
Converted["_Value"].TextSize = 14
Converted["_Value"].TextTransparency = 0.5
Converted["_Value"].TextWrapped = true
Converted["_Value"].TextXAlignment = Enum.TextXAlignment.Right
Converted["_Value"].AnchorPoint = Vector2.new(1, 0.5)
Converted["_Value"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Value"].BackgroundTransparency = 1
Converted["_Value"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Value"].BorderSizePixel = 0
Converted["_Value"].Position = UDim2.new(1, 0, 0.400000006, 0)
Converted["_Value"].Size = UDim2.new(0, 42, 0, 12)
Converted["_Value"].Name = "Value"
Converted["_Value"].Parent = Converted["_Slider"]

Converted["_UITextSizeConstraint11"].MaxTextSize = 12
Converted["_UITextSizeConstraint11"].MinTextSize = 12
Converted["_UITextSizeConstraint11"].Parent = Converted["_Value"]

Converted["_Header2"].Image = "rbxassetid://72035547110749"
Converted["_Header2"].ImageTransparency = 0.5
Converted["_Header2"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Header2"].BackgroundTransparency = 1
Converted["_Header2"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Header2"].BorderSizePixel = 0
Converted["_Header2"].Size = UDim2.new(0, 237, 0, 28)
Converted["_Header2"].Name = "Header"
Converted["_Header2"].Parent = Converted["_Module"]

Converted["_Arrow1"].Image = "rbxassetid://136776761805636"
Converted["_Arrow1"].ImageTransparency = 0.5
Converted["_Arrow1"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Arrow1"].BackgroundTransparency = 1
Converted["_Arrow1"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Arrow1"].BorderSizePixel = 0
Converted["_Arrow1"].Position = UDim2.new(0.899999976, 0, 0.286000013, 0)
Converted["_Arrow1"].Rotation = -90
Converted["_Arrow1"].Size = UDim2.new(0, 11, 0, 11)
Converted["_Arrow1"].Name = "Arrow"
Converted["_Arrow1"].Parent = Converted["_Header2"]

Converted["_Keybind"].Font = Enum.Font.SourceSans
Converted["_Keybind"].Text = ""
Converted["_Keybind"].TextColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Keybind"].TextSize = 14
Converted["_Keybind"].AutoButtonColor = false
Converted["_Keybind"].AnchorPoint = Vector2.new(0, 0.5)
Converted["_Keybind"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Keybind"].BackgroundTransparency = 1
Converted["_Keybind"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Keybind"].BorderSizePixel = 0
Converted["_Keybind"].Position = UDim2.new(0, 0, 0.5, 0)
Converted["_Keybind"].Size = UDim2.new(0, 33, 0, 28)
Converted["_Keybind"].Name = "Keybind"
Converted["_Keybind"].Parent = Converted["_Header2"]

Converted["_Background"].AnchorPoint = Vector2.new(0.5, 0.5)
Converted["_Background"].BackgroundColor3 = Color3.fromRGB(62.00000010430813, 62.00000010430813, 62.00000010430813)
Converted["_Background"].BackgroundTransparency = 0.5
Converted["_Background"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Background"].BorderSizePixel = 0
Converted["_Background"].Position = UDim2.new(0.5, 0, 0.5, 0)
Converted["_Background"].Size = UDim2.new(0, 20, 0, 20)
Converted["_Background"].Name = "Background"
Converted["_Background"].Parent = Converted["_Keybind"]

Converted["_UICorner9"].CornerRadius = UDim.new(0, 4)
Converted["_UICorner9"].Parent = Converted["_Background"]

Converted["_String"].Font = Enum.Font.Unknown
Converted["_String"].Text = "R"
Converted["_String"].TextColor3 = Color3.fromRGB(255, 255, 255)
Converted["_String"].TextSize = 10
Converted["_String"].TextTransparency = 0.5
Converted["_String"].AnchorPoint = Vector2.new(0.5, 0.5)
Converted["_String"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_String"].BackgroundTransparency = 1
Converted["_String"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_String"].BorderSizePixel = 0
Converted["_String"].Position = UDim2.new(0.5, 0, 0.5, 0)
Converted["_String"].Size = UDim2.new(0, 12, 0, 12)
Converted["_String"].Visible = false
Converted["_String"].Name = "String"
Converted["_String"].Parent = Converted["_Background"]

Converted["_UITextSizeConstraint12"].MaxTextSize = 11
Converted["_UITextSizeConstraint12"].MinTextSize = 11
Converted["_UITextSizeConstraint12"].Parent = Converted["_String"]

Converted["_Delete"].Image = "rbxassetid://79831062733212"
Converted["_Delete"].AnchorPoint = Vector2.new(0.5, 0.5)
Converted["_Delete"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Delete"].BackgroundTransparency = 1
Converted["_Delete"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Delete"].BorderSizePixel = 0
Converted["_Delete"].Position = UDim2.new(0.5, 0, 0.5, 0)
Converted["_Delete"].Size = UDim2.new(0, 10, 0, 10)
Converted["_Delete"].Visible = false
Converted["_Delete"].Name = "Delete"
Converted["_Delete"].Parent = Converted["_Background"]

Converted["_Edit"].Image = "rbxassetid://10734887784"
Converted["_Edit"].AnchorPoint = Vector2.new(0.5, 0.5)
Converted["_Edit"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Edit"].BackgroundTransparency = 1
Converted["_Edit"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Edit"].BorderSizePixel = 0
Converted["_Edit"].Position = UDim2.new(0.5, 0, 0.5, 0)
Converted["_Edit"].Size = UDim2.new(0, 10, 0, 10)
Converted["_Edit"].Name = "Edit"
Converted["_Edit"].Parent = Converted["_Background"]

Converted["_Title3"].Font = Enum.Font.Unknown
Converted["_Title3"].Text = "Auto Parry"
Converted["_Title3"].TextColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Title3"].TextScaled = true
Converted["_Title3"].TextSize = 14
Converted["_Title3"].TextTransparency = 0.5
Converted["_Title3"].TextWrapped = true
Converted["_Title3"].TextXAlignment = Enum.TextXAlignment.Left
Converted["_Title3"].AnchorPoint = Vector2.new(0, 0.5)
Converted["_Title3"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Title3"].BackgroundTransparency = 1
Converted["_Title3"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Title3"].BorderSizePixel = 0
Converted["_Title3"].Position = UDim2.new(1, 0, 0.5, 0)
Converted["_Title3"].Size = UDim2.new(0, 156, 0, 12)
Converted["_Title3"].Name = "Title"
Converted["_Title3"].Parent = Converted["_Keybind"]

Converted["_UITextSizeConstraint13"].MaxTextSize = 12
Converted["_UITextSizeConstraint13"].MinTextSize = 12
Converted["_UITextSizeConstraint13"].Parent = Converted["_Title3"]

Converted["_RightSection"].AutomaticCanvasSize = Enum.AutomaticSize.XY
Converted["_RightSection"].CanvasSize = UDim2.new(0, 0, 0.5, 0)
Converted["_RightSection"].ScrollBarImageColor3 = Color3.fromRGB(0, 0, 0)
Converted["_RightSection"].ScrollBarImageTransparency = 1
Converted["_RightSection"].ScrollBarThickness = 0
Converted["_RightSection"].Active = true
Converted["_RightSection"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_RightSection"].BackgroundTransparency = 1
Converted["_RightSection"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_RightSection"].BorderSizePixel = 0
Converted["_RightSection"].Position = UDim2.new(0.620000005, 0, 0.109999999, 0)
Converted["_RightSection"].Size = UDim2.new(0, 237, 0, 306)
Converted["_RightSection"].Name = "RightSection"
Converted["_RightSection"].Parent = Converted["_Sections"]

Converted["_UIListLayout4"].Padding = UDim.new(0, 6)
Converted["_UIListLayout4"].SortOrder = Enum.SortOrder.LayoutOrder
Converted["_UIListLayout4"].Parent = Converted["_RightSection"]

Converted["_UIScale"].Parent = Converted["_Container"]

Converted["_UIAspectRatioConstraint"].AspectRatio = 1.8028168678283691
Converted["_UIAspectRatioConstraint"].Parent = Converted["_Flow"]

Converted["_Mobile"].Font = Enum.Font.SourceSans
Converted["_Mobile"].Text = ""
Converted["_Mobile"].TextColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Mobile"].TextSize = 14
Converted["_Mobile"].AutoButtonColor = false
Converted["_Mobile"].AnchorPoint = Vector2.new(0.5, 0)
Converted["_Mobile"].BackgroundColor3 = Color3.fromRGB(13.000000175088644, 13.000000175088644, 13.000000175088644)
Converted["_Mobile"].BackgroundTransparency = 0.10000000149011612
Converted["_Mobile"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Mobile"].BorderSizePixel = 0
Converted["_Mobile"].Position = UDim2.new(0.5, 0, 0.902557433, 0)
Converted["_Mobile"].Size = UDim2.new(0.0360920988, 0, 0.0440097786, 0)
Converted["_Mobile"].Name = "Mobile"
Converted["_Mobile"].Parent = Converted["_Flow"]

Converted["_UICorner10"].CornerRadius = UDim.new(0, 10)
Converted["_UICorner10"].Parent = Converted["_Mobile"]

Converted["_Icon2"].Image = "rbxassetid://85235558678018"
Converted["_Icon2"].ImageTransparency = 0.4000000059604645
Converted["_Icon2"].AnchorPoint = Vector2.new(0.5, 0.5)
Converted["_Icon2"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Icon2"].BackgroundTransparency = 1
Converted["_Icon2"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Icon2"].BorderSizePixel = 0
Converted["_Icon2"].Position = UDim2.new(0.5, 0, 0.5, 0)
Converted["_Icon2"].Size = UDim2.new(0.258620679, 0, 0.5, 0)
Converted["_Icon2"].Name = "Icon"
Converted["_Icon2"].Parent = Converted["_Mobile"]

Converted["_UIAspectRatioConstraint1"].AspectRatio = 1.6111111640930176
Converted["_UIAspectRatioConstraint1"].Parent = Converted["_Mobile"]
